#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bash .config/polybar/launch.sh --cuts &
nitrogen --restore archwallpaper.png
picom &
/usr/bin/dunst &
#nm-applet & 

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true # focus with mouse

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a dolphin state=floating
bspc rule -a alacritty state=floating
bspc rule -a Nitrogen state=floating center=true
bspc rule -a gwenview state=floating center=true # image viewer
bspc rule -a Arandr state=floating 
bspc rule -a Matplotlib state=floating

#### BSPWM coloring ####
#bspc config normal_border_color		      "#4c566a"
bspc config normal_border_color		      "#d5d5d5"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#a89984"
#bspc config focused_border_color	      "#dfbf8e"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

